### ISSUE TITLE
Hello authors, can you provide a weight file for training with Res-net34.

### ISSUE THREAD

**Issue by MrG27-web** [irtrailenium/train-ego-path-detection#1]
Hello authors, can you provide a weight file for training with Res-net34。

**Comment by GreatTommy** [comment]
Hello MrG27-web,
Unfortunately, we don't provide trained weights for the ResNet-34 backbone as part of this work. However, you can easily reproduce the training process by following the instructions in the [README](https://github.com/irtrailenium/train-ego-path-detection/blob/master/README.md) file. If you have any questions or need further assistance, feel free to ask!

**Comment by MrG27-web** [comment]
> Hello MrG27-web, Unfortunately, we don't provide trained weights for the ResNet-34 backbone as part of this work. However, you can easily reproduce the training process by following the instructions in the [README](https://github.com/irtrailenium/train-ego-path-detection/blob/master/README.md) file. If you have any questions or need further assistance, feel free to ask!

Hello Thomas,

Thank you for your reply. When performing video inference, I have found that uncertainty increases when a train passes through a switch. To address this issue, I have considered a strategy: using the track regression results from the previous frames to crop the next frame's image, thereby hiding the surrounding tracks, and using the cropped image for subsequent inference. In this way, the model focuses only on the area that the train is likely to pass through during inference. However, I have encountered a problem: while it has some effect at the beginning, over time, the errors from this cropping method accumulate, leading to the subsequent cropping hiding the correct areas and an inability to correctly recognize the tracks.

Do you have any suggestions for this approach?

**Comment by GreatTommy** [comment]
Hello MrG27-web,

Indeed, the problem you describe is discussed in section "VII. PRACTICAL USE / B. Limitations" of the paper. Regarding the cropping strategy, a "dynamic cropping" algorithm is described in section "VII. PRACTICAL USE / A. Image Cropping". The key to preventing collapse due to prediction errors is to keep track of the running average of the predicted ego-paths. An implementation of this algorithm can be found [in this repo](https://github.com/irtrailenium/train-ego-path-detection/blob/master/src/utils/autocrop.py).

To better handle uncertainty when the train passes over a switch, I can suggest a few research directions to improve the model:

- Adding a [confidence score](https://arxiv.org/abs/1802.04865) to the predictions.
- Enabling the prediction of [multiple ego-path hypotheses](https://arxiv.org/pdf/1809.10732).
- Using a Kalman filter to stabilize predictions.
- Developing a temporal model.

Good luck!
